# Generated by Django 5.2.4 on 2025-07-21 19:50

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normapy', '0002_importacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacion',
            name='archivo_original',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='uploads/'), upload_to='importaciones/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='importacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='normapy.importacion'),
        ),
    ]
