# Generated by Django 5.2.4 on 2025-07-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normapy', '0003_importacion_archivo_original_producto_importacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('productos_importados', models.IntegerField()),
                ('errores', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
