# Generated by Django 5.2.4 on 2025-07-22 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normapy', '0004_historialimportacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importacion',
            old_name='total_productos',
            new_name='cantidad_productos',
        ),
        migrations.RenameField(
            model_name='importacion',
            old_name='archivo_nombre',
            new_name='nombre_original',
        ),
        migrations.RemoveField(
            model_name='importacion',
            name='archivo_original',
        ),
        migrations.RemoveField(
            model_name='importacion',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='importacion',
            name='usuario',
        ),
        migrations.AddField(
            model_name='importacion',
            name='archivo',
            field=models.FileField(default='importaciones/placeholder.txt', upload_to='importaciones/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacion',
            name='columnas_detectadas',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacion',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacion',
            name='se_generaron_skus',
            field=models.BooleanField(default=False),
        ),
    ]
