# Generated by Django 5.2.4 on 2025-07-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "normapy",
            "0005_rename_total_productos_importacion_cantidad_productos_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="precio",
            field=models.FloatField(),
        ),
    ]
